PREVIEW_HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trip Recap</title>
<link href="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.css" rel="stylesheet"><script src="https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js"></script>
<style>html,body{margin:0;background:#0b0d10;color:#f5f7fa;font-family:system-ui,sans-serif;height:100%}#shell{display:grid;grid-template-rows:auto 1fr;height:100vh}#toolbar{padding:12px 16px;background:#11151a;display:flex;gap:12px;align-items:center;flex-wrap:wrap}#map{height:100%}button,input{font:inherit}button{padding:8px 14px;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}#status{opacity:.8}.scooter{font-size:28px;transform-origin:center}#media-card{position:absolute;z-index:5;left:50%;bottom:24px;transform:translateX(-50%);max-width:min(82vw,760px);max-height:42vh;background:#111;border-radius:14px;padding:8px;display:none;box-shadow:0 10px 40px #0008}#media-card img,#media-card video{display:block;max-width:100%;max-height:38vh;border-radius:10px}#download{color:#fff}</style></head>
<body><div id="shell"><div id="toolbar"><input id="files" type="file" multiple accept="image/*,video/*"><button id="analyze">Analyze trip</button><button id="replay" disabled>Replay</button><button id="render" disabled>Export MP4</button><a id="download" hidden>Download MP4</a><span id="status">Choose original photos/videos with location metadata.</span></div><div style="position:relative;min-height:0"><div id="map"></div><div id="media-card"></div></div></div>
<script>
const params=new URLSearchParams(location.search);const renderMode=params.get('render')==='1';if(renderMode){document.getElementById('toolbar').style.display='none';document.getElementById('shell').style.gridTemplateRows='1fr';}
const map=new maplibregl.Map({container:'map',style:'https://demotiles.maplibre.org/style.json',center:[85.324,27.676],zoom:8,attributionControl:false});
const statusEl=document.getElementById('status'),replay=document.getElementById('replay'),renderBtn=document.getElementById('render'),download=document.getElementById('download'),mediaCard=document.getElementById('media-card');let marker=null,trip=null,route=null,timeline=null,tripId=null,raf=null;window.tripReady=false;
function bearing(a,b){return Math.atan2(b[0]-a[0],b[1]-a[1])*180/Math.PI;}function hideMedia(){mediaCard.style.display='none';mediaCard.innerHTML='';delete mediaCard.dataset.mediaId;}
function showMedia(media){hideMedia();const url=`/api/trips/${tripId}/media/${media.id}`;mediaCard.innerHTML=media.media_type==='video'?`<video src="${url}" preload="auto" muted playsinline></video>`:`<img src="${url}" alt="${media.filename}">`;mediaCard.dataset.mediaId=media.id;mediaCard.style.display='block';}
async function seekVideo(video,time){if(!Number.isFinite(video.duration)){await new Promise(resolve=>{video.addEventListener('loadedmetadata',resolve,{once:true});setTimeout(resolve,1500);});}const max=Number.isFinite(video.duration)?Math.max(0,video.duration-.05):time;const target=Math.max(0,Math.min(time,max));if(Math.abs((video.currentTime||0)-target)<.04)return;await new Promise(resolve=>{const done=()=>resolve();video.addEventListener('seeked',done,{once:true});setTimeout(done,1000);try{video.currentTime=target;}catch{resolve();}});}
function installRoute(){const data=route||{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[]}},empty={type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[]}};if(map.getSource('route')){map.getSource('route').setData(data);map.getSource('traveled').setData(empty);}else{map.addSource('route',{type:'geojson',data});map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#6b7280','line-width':5,'line-opacity':.3}});map.addSource('traveled',{type:'geojson',data:empty});map.addLayer({id:'traveled',type:'line',source:'traveled',paint:{'line-color':'#111827','line-width':7}});}const coords=data.geometry.coordinates;if(coords.length){const bounds=coords.reduce((b,c)=>b.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));map.fitBounds(bounds,{padding:70,duration:renderMode?0:700});if(!marker){const el=document.createElement('div');el.className='scooter';el.textContent='🛵';marker=new maplibregl.Marker({element:el,rotationAlignment:'map'}).setLngLat(coords[0]).addTo(map);}else marker.setLngLat(coords[0]);}}
window.setTripProgress=function(progress){if(!route)return;const coords=route.geometry.coordinates;if(!coords.length)return;const p=Math.max(0,Math.min(1,progress)),raw=p*(coords.length-1),i=Math.min(Math.floor(raw),Math.max(coords.length-2,0)),t=raw-i,a=coords[i],b=coords[Math.min(i+1,coords.length-1)],pos=[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];marker?.setLngLat(pos).setRotation(bearing(a,b));const traveled=coords.slice(0,i+1).concat([pos]);map.getSource('traveled')?.setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:traveled}});};
window.setTripTime=async function(seconds){if(!timeline)return;const duration=Math.max(timeline.duration_seconds,.001),time=Math.max(0,Math.min(duration,seconds));window.setTripProgress(time/duration);let visible=null;for(const e of timeline.events){if(e.video_time>time)break;if(e.type==='media_show')visible=e;if(e.type==='media_hide'&&visible?.payload.media_id===e.payload.media_id)visible=null;}if(!visible){hideMedia();return;}const media=trip.media.find(item=>item.id===visible.payload.media_id);if(!media){hideMedia();return;}if(mediaCard.dataset.mediaId!==media.id)showMedia(media);if(media.media_type==='video'){const video=mediaCard.querySelector('video');const clipTime=Math.min(Math.max(time-visible.video_time,0),Math.min(media.duration_seconds||5,5));if(video)await seekVideo(video,clipTime);}};
function animate(){cancelAnimationFrame(raf);const start=performance.now(),duration=Math.max((timeline?.duration_seconds||20)*1000,4000);function frame(now){const elapsed=Math.min(duration,now-start);window.setTripTime(elapsed/1000);if(elapsed<duration)raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);}
async function loadTrip(id){tripId=id;const [tripRes,routeRes,timelineRes]=await Promise.all([fetch(`/api/trips/${id}`),fetch(`/api/trips/${id}/route`),fetch(`/api/trips/${id}/timeline`)]);trip=await tripRes.json();route=routeRes.ok?await routeRes.json():null;timeline=await timelineRes.json();installRoute();replay.disabled=false;renderBtn.disabled=false;window.tripData=trip;window.routeData=route;window.timelineData=timeline;window.tripReady=true;if(!renderMode)animate();}
async function pollRender(id){for(;;){const r=await fetch(`/api/renders/${id}`),job=await r.json();statusEl.textContent=`Render: ${job.status}`;if(job.status==='complete'){download.href=`/api/renders/${id}/video`;download.hidden=false;download.textContent='Download MP4';renderBtn.disabled=false;return;}if(job.status==='failed'){statusEl.textContent=`Render failed: ${job.error||'unknown error'}`;renderBtn.disabled=false;return;}await new Promise(resolve=>setTimeout(resolve,2000));}}
replay.onclick=animate;renderBtn.onclick=async()=>{if(!tripId)return;renderBtn.disabled=true;download.hidden=true;statusEl.textContent='Starting render…';const response=await fetch(`/api/trips/${tripId}/render`,{method:'POST'}),job=await response.json();if(!response.ok){statusEl.textContent=job.detail||'Render failed to start';renderBtn.disabled=false;return;}pollRender(job.id);};
document.getElementById('analyze').onclick=async()=>{const files=document.getElementById('files').files;if(!files.length)return;const body=new FormData();for(const file of files)body.append('files',file);statusEl.textContent='Extracting metadata and reconstructing trip…';const response=await fetch('/api/trips/analyze',{method:'POST',body}),payload=await response.json();if(!response.ok){statusEl.textContent=payload.detail||'Analysis failed';return;}const first=payload.trips[0];statusEl.textContent=`${first.media_count} media · ${Math.round(first.distance_meters/1000)} km`;await loadTrip(first.id);};
map.on('load',()=>{if(params.get('trip_id'))loadTrip(params.get('trip_id'));});
</script></body></html>'''
